platform :ios, "8.0"
use_frameworks!

target "Bonday" do
#下载进度loading
pod 'SVProgressHUD'


#json解析类
pod 'SwiftyJSON', '~> 4.0.0'

#自动布局 masonry推荐
pod 'SnapKit', '~> 4.0.0'

#图片下载缓存 来自SDWebimage
pod 'Kingfisher', '4.6.1'

#加载指示器
pod 'NVActivityIndicatorView'

#把json对象映射为model对象 他包含下载 ObjectMapper 和 Alamofire
pod 'AlamofireObjectMapper'
pod 'RxSwift',    '~> 4.1.2'
pod 'RxCocoa',    '~> 4.1.2'
pod 'Moya/RxSwift',       '~> 11.0.0'
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'

end
